"use client"
import { CheckCircle2, KeyRound, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import DashboardLayout from '../components/DashboardLayout'
import { api, errorMessage } from '../lib/api'

export default function Activate() {
  const [code, setCode] = useState(''); const [vehicleId, setVehicleId] = useState(''); const [vehicles, setVehicles] = useState([]); const [status, setStatus] = useState({ error: '', success: '' })
  useEffect(() => { api.get('/vehicles').then(({ data }) => setVehicles(data)) }, [])
  const submit = async (event) => { event.preventDefault(); try { const { data } = await api.post('/stickers/activate', { activation_code: code, vehicle_id: vehicleId || null }); setStatus({ success: `Sticker ${data.qr_id} is now active.`, error: '' }) } catch (error) { setStatus({ error: errorMessage(error), success: '' }) } }
  return <DashboardLayout eyebrow="Setup" title="Activate sticker"><div className="mx-auto grid max-w-4xl gap-6 lg:grid-cols-[1.1fr_.9fr]"><form onSubmit={submit} className="card p-7 md:p-10"><span className="grid h-12 w-12 place-items-center rounded-xl bg-cyan-50 text-cyan-650"><KeyRound /></span><h2 className="mt-7 font-display text-2xl font-extrabold">Link your sticker</h2><p className="mt-2 text-sm leading-6 text-black/45">Enter the one-time code printed inside your CarPing package.</p><label className="mt-8 block text-xs font-bold uppercase tracking-wider text-black/50">Activation code</label><input className="field mt-2 font-mono uppercase tracking-[.18em]" placeholder="ABCD-XYZ-123" value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} required /><label className="mt-5 block text-xs font-bold uppercase tracking-wider text-black/50">Link to vehicle (optional)</label><select className="field mt-2" value={vehicleId} onChange={(e) => setVehicleId(e.target.value)}><option value="">Choose later</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.nickname} — {vehicle.vehicle_number}</option>)}</select>{status.error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-650">{status.error}</p>}{status.success && <p className="mt-4 flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 size={17} />{status.success}</p>}<button className="btn-primary mt-6 w-full">Activate securely</button></form><div className="rounded-2xl bg-slate-900 p-8 text-white"><ShieldCheck className="text-cyan-400" size={32} /><h3 className="mt-8 font-display text-2xl font-bold">One code.<br />One owner.</h3><p className="mt-4 text-sm leading-7 text-white/50">Activation codes are cryptographically hashed and can only be claimed once. Your sticker remains under your control until an authorized transfer.</p><div className="mt-8 border-t border-white/10 pt-6 text-xs leading-6 text-white/35">Never share your activation code. CarPing support will never ask for it.</div></div></div></DashboardLayout>
}

