"use client"
import { Ban, Download, QrCode, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import DashboardLayout from '../components/DashboardLayout'
import { api, errorMessage } from '../lib/api'

export default function Admin() {
  const [users, setUsers] = useState([]); const [vehicles, setVehicles] = useState([]); const [batch, setBatch] = useState([]); const [quantity, setQuantity] = useState(10); const [error, setError] = useState('')
  useEffect(() => { api.get('/admin/users').then(({ data }) => setUsers(data.items)); api.get('/admin/vehicles').then(({ data }) => setVehicles(data.items)) }, [])
  const generate = async () => { try { const { data } = await api.post('/admin/stickers/batch', { quantity: Number(quantity), prefix: 'CAR' }); setBatch(data.stickers) } catch (err) { setError(errorMessage(err)) } }
  const exportBatch = () => { const content = ['qr_id,activation_code', ...batch.map((item) => `${item.qr_id},${item.activation_code}`)].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv' })); link.download = 'carping-stickers.csv'; link.click() }
  return <DashboardLayout eyebrow="Operations" title="Admin panel"><div className="grid gap-5 lg:grid-cols-3"><div className="card p-6 lg:col-span-2"><div className="flex items-center justify-between"><div><p className="font-display text-lg font-bold">Sticker generator</p><p className="text-xs text-black/40">Create one-time activation inventory</p></div><QrCode className="text-cyan-600" /></div><div className="mt-6 flex gap-3"><input type="number" min="1" max="1000" className="field" value={quantity} onChange={(e) => setQuantity(e.target.value)} /><button className="btn-primary whitespace-nowrap" onClick={generate}>Generate batch</button></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}{batch.length > 0 && <div className="mt-6"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">{batch.length} stickers generated</p><button onClick={exportBatch} className="flex items-center gap-2 text-xs font-bold text-cyan-600"><Download size={14} /> Export CSV</button></div><div className="max-h-56 overflow-auto rounded-xl border border-black/5">{batch.map((item) => <div key={item.qr_id} className="grid grid-cols-2 border-b border-black/5 px-4 py-2 text-xs"><span className="font-mono">{item.qr_id}</span><span className="font-mono font-bold">{item.activation_code}</span></div>)}</div></div>}</div><div className="card p-6"><Users className="text-cyan-600" /><p className="mt-6 font-display text-4xl font-extrabold">{users.length}</p><p className="text-sm text-black/40">Registered accounts</p><div className="mt-5 border-t border-black/5 pt-5"><p className="font-display text-3xl font-extrabold">{vehicles.length}</p><p className="text-sm text-black/40">Vehicles managed</p></div></div></div>
    <div className="card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-black/5 p-6"><div><p className="font-display text-lg font-bold">Users</p><p className="text-xs text-black/40">Latest registered accounts</p></div><Ban size={17} className="text-black/20" /></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-black/[.025] text-[10px] uppercase tracking-wider text-black/35"><tr><th className="px-6 py-3">Name</th><th>Email</th><th>Mobile</th><th>Role</th><th>Verified</th></tr></thead><tbody>{users.map((user) => <tr className="border-t border-black/5" key={user.id}><td className="px-6 py-4 font-semibold">{user.name}</td><td className="text-black/50">{user.email}</td><td className="text-black/50">{user.mobile}</td><td className="capitalize">{user.role}</td><td>{user.email_verified ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div></div>
  </DashboardLayout>
}

