"use client"
import { Activity, ArrowUpRight, BellRing, Car, QrCode, Tag } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import DashboardLayout from '../components/DashboardLayout'
import { api } from '../lib/api'

const fallbackChart = [{ label: 'Mon', value: 2 }, { label: 'Tue', value: 5 }, { label: 'Wed', value: 3 }, { label: 'Thu', value: 7 }, { label: 'Fri', value: 4 }, { label: 'Sat', value: 9 }, { label: 'Sun', value: 6 }]
const labels = { blocking: 'Vehicle blocking access', headlights: 'Headlights left on', emergency: 'Emergency', flat_tyre: 'Flat tyre', accident: 'Accident damage', custom: 'Custom message' }

export default function Dashboard() {
  const [summary, setSummary] = useState(null); const [chart, setChart] = useState([]); const [period, setPeriod] = useState('daily')
  useEffect(() => { api.get('/dashboard/summary').then(({ data }) => setSummary(data)); api.get(`/dashboard/analytics?period=${period}`).then(({ data }) => setChart(data.points)) }, [period])
  const stats = [{ label: 'Total scans', value: summary?.total_scans || 0, icon: QrCode }, { label: 'Linked vehicles', value: summary?.linked_vehicles || 0, icon: Car }, { label: 'Active stickers', value: summary?.active_stickers || 0, icon: Tag }, { label: 'Unread alerts', value: summary?.unread_notifications || 0, icon: BellRing }]
  return <DashboardLayout eyebrow="Owner portal" title="Overview"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon }) => <div className="card p-5" key={label}><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-50 text-cyan-650"><Icon size={19} /></span><ArrowUpRight size={16} className="text-black/25" /></div><p className="mt-6 font-display text-3xl font-extrabold">{value}</p><p className="mt-1 text-sm text-black/45">{label}</p></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><section className="card p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-display text-lg font-bold">Request activity</p><p className="text-xs text-black/40">Anonymous contacts over time</p></div><div className="flex rounded-lg bg-black/[.04] p-1">{['daily', 'weekly', 'monthly'].map((item) => <button key={item} onClick={() => setPeriod(item)} className={`rounded-md px-3 py-1.5 text-xs font-semibold capitalize ${period === item ? 'bg-white shadow-sm text-slate-800' : 'text-black/40'}`}>{item}</button>)}</div></div><div className="mt-8 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart.length ? chart : fallbackChart}><defs><linearGradient id="cyan" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#06b6d4" stopOpacity={.35} /><stop offset="95%" stopColor="#06b6d4" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eee" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#999' }} /><Tooltip contentStyle={{ borderRadius: 12, border: 0, boxShadow: '0 8px 30px #0001' }} /><Area type="monotone" dataKey="value" stroke="#0891b2" strokeWidth={2.5} fill="url(#cyan)" /></AreaChart></ResponsiveContainer></div></section>
      <section className="card p-5 md:p-7"><div className="flex items-center justify-between"><div><p className="font-display text-lg font-bold">Recent alerts</p><p className="text-xs text-black/40">Latest contact requests</p></div><Activity size={18} className="text-cyan-600" /></div><div className="mt-5 divide-y divide-black/[.06]">{summary?.recent_requests?.length ? summary.recent_requests.slice(0, 5).map((item) => <div key={item.id} className="flex gap-3 py-4"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-cyan-400" /><div><p className="text-sm font-semibold">{labels[item.message_type]}</p><p className="mt-1 text-xs text-black/40">{new Date(item.created_at).toLocaleString()}</p></div></div>) : <div className="py-12 text-center"><BellRing className="mx-auto text-black/15" /><p className="mt-3 text-sm text-black/35">No alerts yet</p></div>}</div></section></div>
  </DashboardLayout>
}

