"use client"
import { Car, Edit3, Plus, Trash2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import DashboardLayout from '../components/DashboardLayout'
import { api, errorMessage } from '../lib/api'

const empty = { vehicle_number: '', vehicle_type: 'car', vehicle_brand: '', vehicle_model: '', nickname: '' }
export default function Vehicles() {
  const [vehicles, setVehicles] = useState([]); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [error, setError] = useState('')
  const load = () => api.get('/vehicles').then(({ data }) => setVehicles(data)); useEffect(() => { load() }, [])
  const save = async (event) => { event.preventDefault(); setError(''); try { editing ? await api.patch(`/vehicles/${editing}`, form) : await api.post('/vehicles', form); setOpen(false); setForm(empty); setEditing(null); load() } catch (err) { setError(errorMessage(err)) } }
  const edit = (vehicle) => { setForm({ vehicle_number: vehicle.vehicle_number, vehicle_type: vehicle.vehicle_type, vehicle_brand: vehicle.vehicle_brand, vehicle_model: vehicle.vehicle_model, nickname: vehicle.nickname }); setEditing(vehicle.id); setOpen(true) }
  const remove = async (id) => { if (window.confirm('Remove this vehicle?')) { await api.delete(`/vehicles/${id}`); load() } }
  return <DashboardLayout eyebrow="Garage" title="My vehicles"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-xl text-sm text-black/45">Manage vehicles linked to your private CarPing account.</p><button className="btn-primary self-start sm:self-auto shrink-0" onClick={() => { setForm(empty); setEditing(null); setOpen(true) }}><Plus size={16} /> Add vehicle</button></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{vehicles.map((vehicle) => <div className="card overflow-hidden" key={vehicle.id}><div className="flex h-28 items-center justify-between bg-slate-900 p-6 text-white"><span className="grid h-12 w-12 place-items-center rounded-xl bg-white/10 text-cyan-400"><Car /></span><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider">{vehicle.vehicle_type}</span></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-600">{vehicle.nickname}</p><h3 className="mt-2 font-display text-2xl font-extrabold">{vehicle.vehicle_number}</h3><p className="mt-1 text-sm text-black/45">{vehicle.vehicle_brand} {vehicle.vehicle_model}</p><div className="mt-6 flex gap-2"><button onClick={() => edit(vehicle)} className="flex flex-1 items-center justify-center gap-2 rounded-lg border border-black/10 py-2 text-xs font-semibold hover:bg-slate-50 transition"><Edit3 size={14} /> Edit</button><button onClick={() => remove(vehicle.id)} className="grid w-10 place-items-center rounded-lg border border-red-100 text-red-500 hover:bg-red-50 transition"><Trash2 size={14} /></button></div></div></div>)}{!vehicles.length && <div className="card col-span-full py-20 text-center"><Car className="mx-auto text-black/15" size={40} /><p className="mt-4 font-semibold">Your garage is empty</p><p className="mt-1 text-sm text-black/40">Add your first vehicle to get started.</p></div>}</div>
    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-5"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold">{editing ? 'Edit vehicle' : 'Add a vehicle'}</h2><button type="button" onClick={() => setOpen(false)}><X /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className="field" placeholder="Vehicle number" value={form.vehicle_number} onChange={(e) => setForm({ ...form, vehicle_number: e.target.value })} required /><select className="field" value={form.vehicle_type} onChange={(e) => setForm({ ...form, vehicle_type: e.target.value })}><option value="car">Car</option><option value="motorcycle">Motorcycle</option><option value="scooter">Scooter</option><option value="truck">Truck</option><option value="other">Other</option></select><input className="field" placeholder="Brand" value={form.vehicle_brand} onChange={(e) => setForm({ ...form, vehicle_brand: e.target.value })} required /><input className="field" placeholder="Model" value={form.vehicle_model} onChange={(e) => setForm({ ...form, vehicle_model: e.target.value })} required /><input className="field sm:col-span-2" placeholder="Nickname (e.g. Family car)" value={form.nickname} onChange={(e) => setForm({ ...form, nickname: e.target.value })} required /></div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<button className="btn-primary mt-6 w-full">{editing ? 'Save changes' : 'Add vehicle'}</button></form></div>}
  </DashboardLayout>
}

